env:
  browser: true
  es6: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - babel
  - react
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    legacyDecorators: true
    jsx: true
globals:
  require: true
rules:
  react/jsx-closing-bracket-location: [1, 'after-props']
  react/destructuring-assignment:
    - off
  react/prop-types:
    - off
  react/jsx-filename-extension:
    - off
  newline-before-return:
    - error
  comma-dangle:
    - error
  operator-linebreak:
    - error
    - after
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  babel/semi:
    - error
    - never
  no-var:
    - error
  prefer-arrow-callback:
    - error
  no-console:
    - warn
  prefer-const:
    - warn
