language: android
before_install:
- nvm install 10
- node --version
- yes | sdkmanager "platforms;android-23"
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script: 
- npm run ci
- cd android && ./gradlew assembleRelease