language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - ~/.npm
before_script:
  - npm install -g npm@latest
script:
  - npm run lint
#  - npm test
  - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - npx expo publish --non-interactive
